<a href="https://colab.research.google.com/github/sandeepasandy/Data-Analytics-Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


In [ ]:
import numpy as np


In [ ]:
print(np.__version__)

2.1.3


In [ ]:
import numpy as np
numbers = np.array([10,20,30,40,50])
print(numbers)
#ndim is a method used to check the dimensions of an array
print(numbers.ndim)

#This is for 2 dimensional array
arr1 = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr1)
print(arr1.ndim)
#for 3 dimensional
arr = np.array([
    [
        [10,20,30],
        [40,50,60]
    ],
    [
       [70,80,90],
       [100,110,120]
    ],
    [
        [130,140,150],
        [160,170,180]
    ]
]
)
arr.ndim
#shape will get the count of elements of rows and columns and height
arr.shape

[10 20 30 40 50]
1
[[10 20 30]
 [40 50 60]]
2


(3, 2, 3)

In [ ]:
#for getting the shape
numbers.shape
#for getting the range of the elements
arr = np.arange(1,10)
print(arr)
#step method here the 2 will be skipped and print another numbers
arr = np.arange(1,10,2)
print(arr)

#array of zeros
#1D
zeros_1d = np.zeros(5)
print("1D:")
print(zeros_1d)
#2D
zeros_2d = np.zeros((2,3))
print("\n2D:")
print(zeros_2d)
#3D
zeros_3d = np.zeros((2,2,3))
print(zeros_3d)

#array of ones:
#1D
ones_1d = np.ones((5))
print("\n1D:")
print(ones_1d)
#2D
ones_2d = np.ones((2,3))
print("\n2D:")
print(ones_2d)
#3D
ones_3d = np.ones((2,2,3))
print("\n3D:")
print(ones_3d)

#full or constant values
#5 is count
#10 is some number
full_1d = np.full(5,10)
print("1D:")
print(full_1d)
#2D
full_2d = np.full((2,3),7)
print("\n2D:")
print(full_2d)
#3D
full_3d = np.full((2,2,3),100)
print("\n3D:")
print(full_3d)
#reshape:
#1D
arr = np.arange(1,7)
print(arr)
#2D
a=arr.reshape(2,3)
print(a)
#3D
a=arr.reshape(2,3,1)
print(a)
#
arr = np.arange(1,11).reshape(5,2,1)
print(arr)


[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
1D:
[0. 0. 0. 0. 0.]

2D:
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

1D:
[1. 1. 1. 1. 1.]

2D:
[[1. 1. 1.]
 [1. 1. 1.]]

3D:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
1D:
[10 10 10 10 10]

2D:
[[7 7 7]
 [7 7 7]]

3D:
[[[100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]]


In [ ]:
import numpy as np
#1.
arr = np.arange(10,50,5)
print(arr)
#2.
arr = np.arange(2,30,2)
print(arr)
#3.
arr = np.arange(1001,1020)
print(arr)
#4.
arr = np.arange(50,1,-1)
print(arr)
#5.
roll_numbers = np.array([101,102,103,104,105,406,107,108])
print(roll_numbers)
roll_numbers.ndim
roll_numbers.shape
#3D:(1,2,4),(1,4,2),(2,1,4)(2,4,1)(4,1,2),(4,2,1),(1,1,8),(1,8,1),(8,1,1) possibilities
roll_numbers=roll_numbers.reshape(1,2,4)
print(roll_numbers)
#6.
#1D
full_1d = np.full(10,7)
print("\n1D:")
print(full_1d)
#2D
full_2d = np.full((2,3),7)
print("\n2D:")
print(full_2d)
#3D
full_3d = np.full((2,5,1),7)
print("\n3D:")
print(full_3d)
#7.
zeros_2d = np.zeros((1,3))
print("\n2D:")
print(zeros_2d)
#8.
ones_3d = np.ones((2,3,4))
print("\n3D:")
print(ones_3d)

[10 15 20 25 30 35 40 45]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2]
[101 102 103 104 105 406 107 108]
[[[101 102 103 104]
  [105 406 107 108]]]

1D:
[7 7 7 7 7 7 7 7 7 7]

2D:
[[7 7 7]
 [7 7 7]]

3D:
[[[7]
  [7]
  [7]
  [7]
  [7]]

 [[7]
  [7]
  [7]
  [7]
  [7]]]

2D:
[[0. 0. 0.]]

3D:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
import numpy as np
#for getting the datatype
#if we given the float values also the if the dtype is int then it will print
#as integer
arr = np.array([10.9,4,10.6,1,],dtype="int")
print(arr)
print(arr.dtype)
#for float
arr = np.array([10.9,4,10.6,1,],dtype="float")
print(arr)
print(arr.dtype)
#for string
arr = np.array([10.9,4,10.6,1,"sandy"],dtype="str")
print(arr)
print(arr.dtype)
#This is also for string
arr = np.array(["sandy","Prudhvi","shalini","Ram","Raju"],dtype="str")
print(arr)
print(arr.dtype)

[10  4 10  1]
int64
[10.9  4.  10.6  1. ]
float64
['10.9' '4' '10.6' '1' 'sandy']
<U5
['sandy' 'Prudhvi' 'shalini' 'Ram' 'Raju']
<U7


In [ ]:
#28-08-26
#1.identity matrix:square matrix
#if we given eye(3) then it will give 3*3 matrix,if 4 then 4*4 matrix
import numpy as np
arr = np.eye(4)
print(arr)
#2.random:


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#29-08-2026
import numpy as np
#line spacing
arr = np.linspace(0,10,3)
print(arr)
#Array shape
arr = np.array([10,20,30,40])
print(arr.shape)
#array reshape
arr = np.array([10,20,30,40])
print(arr.reshape)
#ravel
arr = np.arange(1,11).reshape(2,5,1)
print(arr)
r = arr.ravel()
print(r)
#Transpose the array
#rows to columns and columns into rows
arr = np.arange(1,11).reshape(2,5,1)
print(arr)
r = arr.T
print(r)
r = arr.ravel()
print(r)
#Data type conversion
#can change the numbers into float or any values
arr = np.array([10,20,30])
new_arr = arr.astype(float)
print(new_arr)
print(new_arr.dtype)
#Indexing
arr = np.array([10,20,30,40,50])
print(arr[0:2])#for getting the first two numbers
print(arr[-2:])#for getting the last two numbers
print(arr[-3:-1])#for getting the middle elements
#indexing in 2-Dimension
arr = np.arange(1,11).reshape(2,5)
print(arr)
print(arr[0,3])
#slicing
#if we mention as 0:1 if there are two rows then it will print only one row
arr = np.arange(1,11).reshape(2,5)
print(arr)
print(arr[1,4])
print(arr[0:1])
print(arr[0:2, 0:4])#slicing in two dimensions
#Modification in single dimension
#whreas here we have given the index5 it will change it into 100
arr = np.arange(10,20)
print(arr)
arr[5]=100
print(arr)
#2D
arr[1:4]=80
print(arr)
#insert
n = np.insert(arr,3,89)
print(n)
#for inserting mutiple values
arr = np.array([10,20,30,40,50])
new_arr = np.insert(arr,2,[100,200])
print(new_arr)
#Delete
#for deleting one element
arr = np.array([10,20,30,40,50])
new_arr = np.delete(arr,2)
print(new_arr)
#for deleting multiple elements
arr = np.array([10,20,30,40,50])
new_arr = np.delete(arr,[2,3])
print(new_arr)

[ 0.  5. 10.]
(4,)
<built-in method reshape of numpy.ndarray object at 0x7c86a67f3030>
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
[ 1  2  3  4  5  6  7  8  9 10]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]
[ 1  2  3  4  5  6  7  8  9 10]
[10. 20. 30.]
float64
[10 20]
[40 50]
[30 40]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
4
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
[[1 2 3 4 5]]
[[1 2 3 4]
 [6 7 8 9]]
[10 11 12 13 14 15 16 17 18 19]
[ 10  11  12  13  14 100  16  17  18  19]
[ 10  80  80  80  14 100  16  17  18  19]
[ 10  80  80  89  80  14 100  16  17  18  19]
[ 10  20 100 200  30  40  50]
[10 20 40 50]
[10 20 50]


In [ ]:
#1
arr = np.linspace(0,100,10)
print(arr)
#2
arr = np.linspace(1,50,15)
print(arr)
#3
arr = np.array([10,20,30,40,50,60,70])
print(arr[0])
print(arr[-1])
print(arr[4])
print(arr[-2])
#4
arr = np.array([10,20,30,40,50,60,70])
print(arr[0:4])
print(arr[2:5])
print(arr[-3])
for i in range(0,len(arr)-1,2):#for getting alternative numbers
  print(arr[i],end= " ")
print(arr[0:7:2])
#5
arr = np.array([
    [10,20,30],[40,50,60],[70,80,90]
])
print(arr[1,1])
print(arr[0,2])
print(arr[2,0])
print(arr[1])
print(arr[2])
print(arr[0,1])


[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]
10
70
50
60
[10 20 30 40]
[30 40 50]
50
10 30 50 [10 30 50 70]
50
30
70
[40 50 60]
[70 80 90]
20


In [ ]:
import numpy as np
#1.
arr = np.arange(1,21)
print(arr)
#2.
arr = np.array([1,2,3])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
#3.
arr = np.zeros(5)
print(arr)
#4.
arr = np.linspace(0,100,5)
print(arr)
#5.
arr = np.arange(1, 21)
new_arr = arr.reshape(4, 5)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
int64
1
(3,)
[0. 0. 0. 0. 0.]
[  0.  25.  50.  75. 100.]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
#56,89 5
arr = np.linspace(56,89,5)
print(arr)

[56.   64.25 72.5  80.75 89.  ]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
ones_2d = np.ones((2,3))
print(ones_2d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#01-09-26
#aggregation functions in numpy
import numpy as np
#1D
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
#2D
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print(np.sum(arr))
#min
print(np.min(arr))
#max
print(np.max(arr))
#sum with axis
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print(arr)
print(np.sum(arr,axis=0))
#mean
#1D
arr = np.array([10,20,30,40,50])
print(np.mean(arr))
#2D
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print(np.mean(arr))
#Variance
#1D
arr = np.array([10,20,30,40,50])
print(np.var(arr))
#2D
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print(np.var(arr))
#standard deviation(std)
#1D
arr = np.array([10,20,30,40,50])
print(np.std(arr))
#2D
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print(np.std(arr))
#percentile:
#0 to 100
#if we give 100 means it will return the max value
#if we give any another number it will give another number
arr = np.array([10,20,30,40,50])
print(np.percentile(arr,50))
#quantile:
#0 to 1 like 0.20,0.30 etc...
np.quantile(arr,0.50)
#argmax
#returns the position of the element in array which is in the highest value
#1D
arr = np.array([10,90,30,70,40])
print(np.argmax(arr))
#2D
arr = np.array([10,90,30,70,40,10]).reshape(2,3)
print(np.argmax(arr))
#argmin
#1D
arr = np.array([10,90,30,70,40])
print(np.argmin(arr))
#2D
#argmin
arr = np.array([10,90,30,70,40,10]).reshape(2,3)
print(np.argmin(arr))
#log10()
#1D
arr = np.array([10,100,1000])
print(np.log10(arr))
#2D
arr = np.array([10,90,30,70,40,60]).reshape(2,3)
print(np.log10(arr))
#log2()
arr = np.array([10,90,30,70,40,60]).reshape(2,3)
print(np.log10(arr))
print(np.log(arr))
print(np.log(2))
print(np.log(3))
#round
arr = np.array([10.25, 20.67,30.93])
print(np.round(arr))

150
210
10
60
[[10 20 30]
 [40 50 60]]
[50 70 90]
30.0
35.0
200.0
291.6666666666667
14.142135623730951
17.07825127659933
30.0
1
1
0
0
[1. 2. 3.]
[[1.         1.95424251 1.47712125]
 [1.84509804 1.60205999 1.77815125]]
[[1.         1.95424251 1.47712125]
 [1.84509804 1.60205999 1.77815125]]
[[2.30258509 4.49980967 3.40119738]
 [4.24849524 3.68887945 4.09434456]]
0.6931471805599453
1.0986122886681098
[10. 21. 31.]


In [ ]:
#round
arr = np.array([10.253, 20.675,30.939])
print(np.round(arr))
print(np.round(arr,2))
#floor
#adjusts to lower limit
arr = np.array([10.2,10.8,20.9])
print(np.floor(arr))
#ceil()
#adjusts to upper limit
arr = np.array([10.2,10.8,20.9])
print(np.ceil(arr))
#abs
#if we given negative numbers also it will only return the positive numbers
arr = np.array([10,-5,6,-19])
print(np.abs(arr))
#sort
#ascending order
arr = np.array([90,120,150,40,10])
result = np.sort(arr)
print(result)
#changing to descending order
arr = np.array([90,120,150,40,10])
result = np.sort(arr)[::-1]
print(result)

[10. 21. 31.]
[10.25 20.68 30.94]
[10. 10. 20.]
[11. 11. 21.]
[10  5  6 19]
[ 10  40  90 120 150]
[150 120  90  40  10]


In [ ]:
#Practice Questions
#1.
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
#2.
marks = np.array([45,78,92,56,88,67,34])
print(np.min(marks))
print(np.max(marks))
#3.
sales = np.array([12000,15000,18000,11000,20000])
print(np.mean(sales))
#4.
data = np.array([10,20,30,40,50])
print(np.var(data))
#5.
marks = np.array([60,70,80,90,100])
print(np.std(marks))
#6.
marks = np.array([35,42,55,60,68,72,80,85,95,100])
print(np.percentile(marks,50))
#7.
salary = np.array([25000,30000,35000,40000,45000,50000])
print(np.quantile)

150
34
92
15200.0
200.0
14.142135623730951
70.0


In [ ]:
#04-09-26
#split 1D array
import numpy as np
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,3)#splits the elements in 3 equal parts
print(result)
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,2)#splits the elements in 2 equal parts
print(result)
#customized splitting
#passing the values in the list
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,[2,4])
print(result)
#split on 2D array
arr = np.array([
    [10,20],
    [30,40],
    [50,60],
    [70,80]
])
result = np.split(arr,2,axis=0)#for rows if we want to do as columns then axis=1
print(result)
#customized splitting on 2d array
arr = np.array([
    [10,20,30],
    [30,40,50],
    [50,60,70],
    [70,80,90]
])
result = np.split(arr,[1,3],axis=1)
print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20, 30]), array([40, 50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]
[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]])]
[array([[10],
       [30],
       [50],
       [70]]), array([[20, 30],
       [40, 50],
       [60, 70],
       [80, 90]]), array([], shape=(4, 0), dtype=int64)]
