<a href="https://colab.research.google.com/github/sandeepasandy/Data-Analytics-Practice/blob/main/Numpy_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
arr.ndim
arr.shape
arr.size
arr.dtype
#2.
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
print(arr)
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]).reshape(2,3,4)
print(arr)
#3.
arr = np.zeros(6).reshape(2,3)
print(arr)
arr = np.zeros(6).reshape(2,3)
print(arr)
arr = np.zeros(8).reshape(2,2,2)
print(arr)
#4.
arr = np.ones(8).reshape(2,4).reshape(2,2,2)
print(arr)
arr.ndim
arr.shape
#5.
arr = np.full((3, 4), 7)
print(arr)
#6.
arr = np.random.rand(10)
print(arr)
#7.
arr = np.random.randint(10,50,(3, 3))
print(arr)
#8.
arr = np.random.randint(2,4)
print(arr)
#9.
colors = ["Red","Blue","Green","Yellow","Black"]
random_colors = np.random.choice(colors,3)
print(random_colors)
#10.

[10 20 30 40 50]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[0.90018181 0.22145482 0.16485936 0.0846078  0.86583118 0.81066425
 0.33545973 0.88507107 0.24428228 0.99263071]
[[29 25 23]
 [39 35 40]
 [17 36 42]]
2
['Yellow' 'Black' 'Yellow']


In [ ]:
#11.
arr = np.random.randint(5,50,(5))
print(arr)
#12.
arr = np.array([10,20,30,40,50,60])
np.random.shuffle(arr)
print(arr)
arr1 = np.random.permutation(arr)
print(arr1)
#13.
arr = np.random.randint(0,100,(6))
print(arr)
#14.
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
print(arr)
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
#15.
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
arr = arr.T
print(arr)
#16.
arr = np.array([10,20,30,40,50])
arr.dtype
arr.astype(float)


[18 40 46 44 35]
[30 10 20 50 40 60]
[60 20 10 30 40 50]
[63  5 77 31  8 96]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


array([10., 20., 30., 40., 50.])

In [ ]:
#17.
arr = np.array([10,20,30],[40,50,60],[70,80,90])